[platformio]
src_dir = .
include_dir = .

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; O projeto ainda usa arquivos .cpp/.h e o DrumOS.ino na raiz.
; Por isso o src_dir aponta para a raiz do repositorio.
build_src_filter =
  +<*.cpp>
  +<*.ino>
  -<.pio/>
  -<.git/>
